INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES  ('Pulp Fiction',  "Quentin Tarentino", "L'odyssée sanglante et burlesque de petits malfrats dans la jungle de Hollywood à travers trois histoires qui s'entremêlent. Dans un restaurant, un couple de jeunes braqueurs, Pumpkin et Yolanda, discutent des risques que comporte leur activité. Deux truands, Jules Winnfield et son ami Vincent Vega, qui revient d'Amsterdam, ont pour mission de récupérer une mallette au contenu mystérieux et de la rapporter à Marsellus Wallace.", 'https://retourverslecinema.com/wp-content/uploads/2013/09/Pulp-fiction-1994.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ('Pulp Fiction',  "Quentin Tarentino", "L'odyssée sanglante et burlesque de petits malfrats dans la jungle de Hollywood à travers trois histoires qui s'entremêlent. Dans un restaurant, un couple de jeunes braqueurs, Pumpkin et Yolanda, discutent des risques que comporte leur activité. Deux truands, Jules Winnfield et son ami Vincent Vega, qui revient d'Amsterdam, ont pour mission de récupérer une mallette au contenu mystérieux et de la rapporter à Marsellus Wallace.", 'https://retourverslecinema.com/wp-content/uploads/2013/09/Pulp-fiction-1994.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ('La colline a des yeux', 'Alexandre Aja', "Pour fêter leur anniversaire de mariage et resserrer du même coup des liens familiaux qui battent de l'aile, toute la famille Carter monte en voiture. Destination : la Californie. Sur les conseils d'un pompiste pas très net, ils vont prendre un raccourci dans le désert du Nouveau-Mexique qui les conduira vers les pires cauchemars.",'https://fr.web.img5.acsta.net/medias/nmedia/18/36/20/39/18609535.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ('Tintin sur la lune', 'Bernard Bald', "L'oeuvre d'Hergé adaptée en Live action. Retrouvez tintin, Milou, le capitaine Haddock en exploration de l'astre solaire. Tintin va prendre une fusée et marcher sur la lune avec son chien (oui oui normal). Les paysages sont plus que réalistes dans cette adaptation",'https://i.ibb.co/kQv0JxY/tintin.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ("Parasite", 'Bong Joon-Ho', "Les différences de classe entre une famille pauvre et une famille aisée apparaissent au grand jour. Lorsque Ki-woo obtient un poste de tuteur chez les riches Parks, il fait en sorte que ses parents et sa soeur soient également engagés. La famille profite du mode de vie luxueux des Parks, mais ils découvrent alors un sombre secret. ",'https://img-4.linternaute.com/uVxdFzpRJ56EW2hYBCls8_5O9zE=/405x540/0156050d180a42b2a0cea23c262949e2/ccmcms-linternaute/175577.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ('Intouchables 2', 'Michel Cheville', "Après un accident dramatique à l'escalde, réré se retrouve à lhopital. Tout le monde se demandait: 'pourquoi a t-il grimpé il n'y avait rien à cueillir?'. Après sa chute il a du compter sur son accolyte sans cheveux",'https://i.ibb.co/dDP149z/intouch.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ('Les aventures de titi', 'Hallé Lille', "Titi s'en va pour de nouvelles aventures et cette fois dans le nord. Cette fois, il ne doit pas échapper à Grosminet mais il doit s'evertuer à comprendre ses nouveaux voisins avec leur accent ch'tis",'https://i.ibb.co/RTKtx26/dylan.png');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ("American Beauty", 'Sam Mendes', "Les Burnham sont en apparence une famille parfaite, menant une petite vie tranquille dans une petite banlieue tranquille. Or, les apparences sont trompeuses et sous la surface les Burnham bouillonnent de frustrations et de désirs cachés.",'https://img-4.linternaute.com/MW58MWmRKXlvyrLw1Q45pRmlzvk=/1240x/65008c82387947f3a6418154e6fcebfd/ccmcms-linternaute/82906.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ("Le traitre (l'affiche spoile le film)", 'Robert Gun', "Une taupe se cache au sein de la brigade 32. Qui, QUI pourrait bien s'infiltrer dans la police? Un être aussi perfide que mauvais gagnant",'https://i.ibb.co/mq2n0cn/rey.png');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ("Le diner de con", 'Francis Veber', "Pierre, éditeur, participe chaque mercredi à un `dîner de cons'. Le principe : chacun amène un `con' et celui qui a déniché le plus spectaculaire est déclaré vainqueur. Ce soir, son invité est François Pignon. Passionné de modèles réduits en allumettes, ce dernier est également un véritable porteur de guigne.",'http://ekladata.com/s4xe5_aOARaOWd7Ybzi77SkvUs0.jpg');
INSERT INTO `movie` (`title`, `director`, `description`, `image`) VALUES ('Les laissés pour compte', 'Véronique doudou', "Documentaire choc sur une maladie méconnus: Le besoin compulsif de porter un doudou sur la tete. Cette maladie touche généralement les hommes approchants la quarantaine et qui n'ont pas assez de cheveux pour se réchauffer quand le frois arrive",'https://i.ibb.co/4FR9CMD/ju.png');

